server:
  port: 8081
spring:
  application:
    name: user-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/astralx_userdb
    username: bankuser
    password: bankpass

