server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
    config:
      server:
              git:
                uri: https://github.com/omeryayla/astralxbank-config-repo
                default-label: main
                search-paths: .


